### ISSUE TITLE
Can't build under Linux

### ISSUE THREAD

**Issue by mholo65** [draylundy/ProtobufGenerator#1]
Having issues with building under Linux fore several reasons.

Some suggestions:
- Consider creating DNX project structure and target ```dnx451``` and ```dnxcore50```
- Move from Visual Studio test project to NUnit or preferably XUnit as it's even better supported under DNX.

I could create a pull request at some point, once we agree on the details :)

**Comment by draylundy** [comment]
Yes, I agree this should be cross-platform. I should add that to a section of project goals in the Read Me. 

I'd be glad to accept a pull request with DNX project structure. I should have made it that way to start with in hindsight. 

With regard to unit testing frameworks I should share context of current development and you can decide whether you want to continue working on an NUnit -> xUnit migration for all the tests I'm currently writing. 

The compiler project is experimental because I took interest in monadic parser combinators after reading a whitepaper. I took a chance on a lightweight implementation (Sprache) that builds the grammar definition all in C# rather than a more conventional lexer / parser generator from EBNF grammar file.

xUnit might make refactoring the unit tests in that project tricky due to the strong opinions they have on unit testing best practices, i.e. explicit assertion of exception location in test method bodies as opposed to ExpectedException attribute. 

For instance, at the moment I'm buying speed with the technical debt of not clearly defining in the unit tests which function in the composition fails for edge cases. 

Motivation for that debt is to get quickly to point where I can evaluate if Sprache was the right fit for the compiler. Then I can either go back and pay the debt or push the debt into the rubbish bin with the implementation.

So you can decide if you want to spend that time before I'm sure the parser is viable.

The Generator should be quite stable though so no problems on that end. 

In any case your efforts are most welcome.

**Comment by mholo65** [comment]
Ok, thanks for the info/heads up. Created a PR #2 where we could continue discussions.

**Comment by draylundy** [comment]
Should now build under Linux. Tested today with Ubuntu 15.04. Let me know if you have any issues next time you build.
