### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by mholo65** [draylundy/ProtobufGenerator#10]
Create Unit Test code coverage report using Open Cover.
https://github.com/OpenCover/opencover/wiki/DNX-Support

I could check into this.

**Comment by draylundy** [comment]
This is now working on Appveyor and pushing results to Coveralls. 

Unfortunately the portable PDBs created with .NET Core do not currently work with coverage analysis tools. That's why I'm doing this on Appveyor and not Travis, have to json transform the debugType to full on the CI server before running coverage.
